app/models.py
from datetime import datetime
from . import db


"""
class MyTestClass(db.Model):
    __tablename__ = 'mytesttable'
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), nullable=False, unique=True, index=True)
    username = db.Column(db.String(64), nullable=False, unique=True, index=True)
    is_admin = db.Column(db.Boolean)
    password_hash = db.Column(db.String(128))
    location = db.Column(db.String(64))
    member_since = db.Column(db.DateTime, default=datetime.utcnow)
    bio = db.Column(db.Text())

    def __init__(self, email, username):
        self.email = email
        self.username = username

    def __repr__(self):
        return '<User %r>' % self.username
"""

app/__init__.py
from flask import Flask
from config import config
from flask.ext.sqlalchemy import SQLAlchemy

# create the database object
db = SQLAlchemy()

# this function is the application factory
def create_app(environment):
    app = Flask(__name__)
    app.config.from_object(config[environment])

    db.init_app(app)

    from bp_main import bp_main
    from bp_another_blueprint import bp_another_blueprint

    app.register_blueprint(bp_main, url_prefix='')
    app.register_blueprint(bp_another_blueprint, url_prefix='/another_bp')

    return app

app/bp_another_blueprint/__init__.py
from flask import Blueprint

bp_another_blueprint = Blueprint('bp_another_blueprint', __name__, template_folder='templates')

from . import views, errors

app/bp_another_blueprint/views.py
from flask import render_template
from . import bp_another_blueprint

@bp_another_blueprint.route('/')
def index():
    return render_template('bp_another_blueprint/index.html')

@bp_another_blueprint.route('/link1')
def link1():
    return render_template('bp_another_blueprint/link1.html')

@bp_another_blueprint.route('/link2')
def link2():
    return render_template('bp_another_blueprint/link2.html')

app/bp_main/__init__.py
from flask import Blueprint

bp_main = Blueprint('bp_main', __name__, template_folder='templates')

from . import views, errors

app/bp_main/views.py
from flask import render_template
from . import bp_main

@bp_main.route('/')
def index():
    return render_template('bp_main/index.html')

@bp_main.route('/link1')
def link1():
    return render_template('bp_main/link1.html')

@bp_main.route('/link2')
def link2():
    return render_template('bp_main/link2.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<meta charset="utf-8" />
		<title>My Flask Skeleton</title>

		<meta name="description" content="" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />

		<!-- bootstrap & fontawesome -->
		<link rel="stylesheet" href="/static/css/bootstrap.min.css" />
		<link rel="stylesheet" href="/static/css/font-awesome.min.css" />

		<!-- page specific plugin styles -->

		<!-- text fonts -->
		<link rel="stylesheet" href="/static/css/ace-fonts.css" />

		<!-- ace styles -->
		<link rel="stylesheet" href="/static/css/ace.min.css" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="/static/css/ace-part2.min.css" />
		<![endif]-->
		<link rel="stylesheet" href="/static/css/ace-skins.min.css" />
		<link rel="stylesheet" href="/static/css/ace-rtl.min.css" />

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="/static/css/ace-ie.min.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->
		<script src="/static/js/ace-extra.min.js"></script>

		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->

		<!--[if lte IE 8]>
		<script src="/static/js/html5shiv.js"></script>
		<script src="/static/js/respond.min.js"></script>
		<![endif]-->
	</head>

	<body class="no-skin">
		<!-- #section:basics/navbar.layout -->
		<div id="navbar" class="navbar navbar-default">
			<script type="text/javascript">
				try{ace.settings.check('navbar' , 'fixed')}catch(e){}
			</script>

			<div class="navbar-container" id="navbar-container">

				<!-- /section:basics/sidebar.mobile.toggle -->
				<div class="navbar-header pull-left">
					<!-- #section:basics/navbar.layout.brand -->
					<a href="#" class="navbar-brand">
						<small>
							<i class="fa fa-car"></i>
							&nbsp;Some Cool Title
						</small>
					</a>
				</div>
				<!-- /section:basics/navbar.dropdown -->
			</div><!-- /.navbar-container -->
		</div>

		<!-- /section:basics/navbar.layout -->
		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<!-- #section:basics/sidebar -->
			<div id="sidebar" class="sidebar responsive">
				<script type="text/javascript">
					try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
				</script>

				<ul class="nav nav-list">
					<li class="">
						<a href="{{ url_for('bp_main.index') }}">
							<i class="menu-icon fa fa-tachometer"></i>
							<span class="menu-text"> Main </span>
						</a>

						<b class="arrow"></b>
					</li>
					<li class="">
						<a href="{{ url_for('bp_another_blueprint.index') }}">
							<i class="menu-icon fa fa-cubes"></i>
							<span class="menu-text"> Another </span>
						</a>

						<b class="arrow"></b>
					</li>

				</ul><!-- /.nav-list -->
			</div>
			<!-- /section:basics/sidebar -->

            <div class="main-content">
				<div class="page-content">
					<div class="row">
						<div class="col-xs-12">
							<!-- PAGE CONTENT BEGINS -->
                                <h1 class="page-header">{% block header_title %}{% endblock %}</h1>
                                {% block header_nav %}{% endblock %}<br><br>
                                {% block content %}{% endblock %}
							<!-- PAGE CONTENT ENDS -->
						</div><!-- /.col -->
					</div><!-- /.row -->
				</div><!-- /.page-content -->
			</div><!-- /.main-content -->
			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="ace-icon fa fa-angle-double-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->
		<script type="text/javascript">
			window.jQuery || document.write("<script src='/static/js/jquery.min.js'>"+"<"+"/script>");
		</script>

		<!-- <![endif]-->

		<!--[if IE]>
        <script type="text/javascript">
         window.jQuery || document.write("<script src='/static/js/jquery1x.min.js'>"+"<"+"/script>");
        </script>
        <![endif]-->
		<script type="text/javascript">
			if('ontouchstart' in document.documentElement) document.write("<script src='/static/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>
		<script src="/static/js/bootstrap.min.js"></script>


		<!-- ace scripts -->
		<script src="/static/js/ace-elements.min.js"></script>
		<script src="/static/js/ace.min.js"></script>


	</body>
</html>

app/templates/bp_another_blueprint/index.html
{% extends "base.html" %}

{% block header_title %}Another Blueprint {% block sub_title %}{% endblock %}{% endblock %}
{% block header_nav %}
    <a href="{{ url_for('bp_another_blueprint.link1') }}">Link 1</a> |
    <a href="{{ url_for('bp_another_blueprint.link2') }}">Link 2</a>
{% endblock %}

{% block content %}

    {% block page_content %} index template {% endblock %}

{% endblock %}

app/templates/bp_another_blueprint/link1.html
{% extends "bp_another_blueprint/index.html" %}

{% block sub_title %} - Link 1 {% endblock %}

{% block page_content %}
    link1 template
{% endblock %}

app/templates/bp_another_blueprint/link2.html
{% extends "bp_another_blueprint/index.html" %}

{% block sub_title %} - Link 2 {% endblock %}

{% block page_content %}
    link2 template
{% endblock %}

app/templates/bp_main/index.html
{% extends "base.html" %}

{% block header_title %}Main {% block sub_title %}{% endblock %}{% endblock %}
{% block header_nav %}
    <a href="{{ url_for('bp_main.link1') }}">Link 1</a> |
    <a href="{{ url_for('bp_main.link2') }}">Link 2</a>
{% endblock %}

{% block content %}

    {% block page_content %} index template {% endblock %}

{% endblock %}

app/templates/bp_main/link1.html
{% extends "bp_main/index.html" %}

{% block sub_title %} - Link 1 {% endblock %}

{% block page_content %}
    link1 template
{% endblock %}

app/templates/bp_main/link2.html
{% extends "bp_main/index.html" %}

{% block sub_title %} - Link 2 {% endblock %}

{% block page_content %}
    link2 template
{% endblock %}